### ISSUE TITLE
Find hash of a commit based on the name of its tag

### ISSUE THREAD

**Issue by vbossica** [Microsoft/vsts-cli#115]
[This question is for the vsts-python-api, as I am writing the corresponding classes for the vsts-cli.] I'm trying to retrieve the Git hash of a commit, knowing only the name of the tag pointing to this commit.

When using the /refs endpoint (filtering for tags), I can only retrieve an _annotated_ tag with the returned ref's object_id.

Is there a way to retrieve a simple tag with a ref's object_id?

**Comment by tedchamb** [comment]
Going forward you can file your vsts-python-api issues directly in the vsts-python-api repo:
https://github.com/Microsoft/vsts-python-api/issues

I have forwarded your question to the git api team, and will get back to you.

**Comment by tedchamb** [comment]
On a side note, we have a new documentation site for the VSTS APIs with examples.  Our python-sdk-api is just a wrapper for the REST apis, so you may find useful information here:

https://docs.microsoft.com/en-us/rest/api/vsts/git/commits

**Comment by WilAtMSFT** [comment]
You can get all the tags from the /refs/tags endpoints. For example, tag1 below is annotated and tag2 is a lightweight:

```
{
value: [
{
name: "refs/tags/tag1",
objectId: "b0fa354e399adc227fe013e3a9e1b4947659beee",
},
{
name: "refs/tags/tag2",
objectId: "6d9ae2bf6883412bab2d389a3b5e1447003944eb",
}
],
count: 2
}
```
In the tag2 case, the objectId is the commit as it is a lightweight tag. In the tag1 case, if we want the commitId we need to crack the annotated tag, which you can do with the annotated tag endpoint (https://docs.microsoft.com/en-us/rest/api/vsts/git/Annotated%20Tags/Get). In my example, if I go to /annotatedtags/b0fa354e399adc227fe013e3a9e1b4947659beee off the repository REST API, I then get the response:

```
{
name: "refs/tags/tag1",
objectId: "b0fa354e399adc227fe013e3a9e1b4947659beee",
taggedObject: {
objectId: "6d9ae2bf6883412bab2d389a3b5e1447003944eb",
objectType: "commit"
},
message: "hello",
}
```
In this result we see that the annotated tag `b0fa354e399adc227fe013e3a9e1b4947659beee` points to the object `6d9ae2bf6883412bab2d389a3b5e1447003944eb` which is a commit. Since annottated tags can point to annotated tags, you may have to follow the chain until you get to the taggedObject being of objectType commit.

**Comment by vbossica** [comment]
@WilAtMSFT @tedchamb thanks for the answer.
It would have been handy to not need to fire another request to distinguish between simple and annotated tags, but it's not an additional request that will make a big difference.
