### ISSUE TITLE
VSTS CLI - potentially dangerous request.path value was detected from the client

### ISSUE THREAD

**Issue by jigneshc** [Microsoft/vsts-cli#161]
When i am using command "vsts code pr list", it is giving me below error
A potentially dangerous request . Path value was detected from the client. Operation returned an invalid status code of 400.

**Comment by tedchamb** [comment]
@jigneshc Thanks for reporting this.  This most likely means that a character or a set of characters that is commonly used in XSS attacks was given in a value you supplied to one of the arguments to the command.  

Can you send us the full command you used that repros the issue?  Before sending you need to scrub any private data in a way that we can still see the potentially dangerous strings in the arguments.  Once we have that information, we should be able to repro, and can double check  that we are escaping the value correctly or whether the set of characters just needs to be avoided.

You can find more information here:
https://msdn.microsoft.com/en-us/library/hh882339(v=vs.110).aspx

**Comment by jigneshc** [comment]
@tedchamb I am using command "vsts code pr list" to get all pull request.
I guess I was giving half command so when I am using command "vsts code pr list --instance https://jigneshc.visualstudio.com --project WebApplication" that time I am getting all pull request.

**Comment by tedchamb** [comment]
Thanks @jigneshc , this is helpful information.  

When you do not supply an instance, the tool will try to determine the instance by the git remote associated with your current working directory.  If there is no git remote associated with the current working directory, then it will see if you have a default instance and project configured for the tool.  If there is no default configured, then you will get an appropriate error, stating that you must specify the instance and/or project.  Since you got the error message that you described, this means that either there is a git remote for the current working directory or you have a default configured.

The first thing to do is to run the command with the `--debug` argument.  When you do this the actual url that you are using will show in the output.  The url being used should be invalid in some way, hence the error message.

To see where this url is coming from, run the following command from the working directory where you can repro the issue: `git remote -v`  Check the results of that command and if there are any remotes listed, see if there are any unusual strings in the url path.

The next thing to check is to run `vsts configure --list`, and see if you have set default values for instance and/or project.  If they are set ensure you have set them to correct values.

If these values are incorrect you can run the following to reset them:
`vsts configure --defaults instance=https://<account>.visualstudio.com`
`vsts configure --defaults project=<projectName>`

Please let me know if this helps you solve the issue.  If this does not solve your issue, please let me know the results of the commands above after scrubbing any private data, and I will investigate further.

Thanks,
Ted

**Comment by jigneshc** [comment]
Thank you @tedchamb above solution is resolving my issue.
Actually, By mistake I set the default project as instance, that's why I am getting potentially damage error.
I check the default by given command:
vsts configure --list

After that I set the default project name using command:
vsts configure --defaults project=<projectName>

And run the below command:
vsts code pr list

Now it is showing me list of pull request.

Thanks a lot.
