### ISSUE TITLE
Login fails when connecting to TFS instance with self-signed certificate

### ISSUE THREAD

**Issue by markjgardner** [Microsoft/vsts-cli#76]
Attempting to login against our local TFS instance which uses a cert signed by an internal/private CA fails. Adding the `--debug` switch confirms my suspicion that the cert isn't trusted. Is there any way to provide an alternate CA bundle? Or to tell the CLI to accept a specific CA or cert?

`urllib3.connectionpool : Retrying (Retry(total=2, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)'),)': /tfs/defaultcollection2/_apis`

**Comment by tedchamb** [comment]
Thanks for reporting this issue.  We will look into providing a fix that will allow you to optionally by pass the cert verification.

**Comment by tedchamb** [comment]
@markjgardner There is a safer way to workaround this issue.  You can take your servers certificate, and copy it to a Base-64 encoded X.509 file (In windows you would open the certificate, go to details tab, and choose 'copy to file...' button).  Then you can set the following environment variable <code>REQUESTS_CA_BUNDLE</code> to the file path of your cert file.  Once this is done you will no longer get verification errors.  Can you give this a try?

**Comment by markjgardner** [comment]
That's exactly what I was looking for, and it works great. Thanks for the follow up.

**Comment by germanilia** [comment]
msrest.exceptions.ClientRequestError: Error occurred in request., SSLError: HTTPSConnectionPool(host='ztest1', port=443): Max retries exceeded with url: /defaultcollection/_git/testinggithooks/vsts/info (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)'),))
ERROR: Error occurred in request., SSLError: HTTPSConnectionPool(host='ztest1', port=443): Max retries exceeded with url: /defaultcollection/_git/testinggithooks/vsts/info (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)'),))


I have the same issue and the proposed solution didn't work for me, any help will be appreciated.

**Comment by cage200** [comment]
In case of Azure Devops multiple links are used and they have different root certificates.How can I add multiple certificates to REQUESTS_CA_BUNDLE ?

**Comment by cage200** [comment]
@davidroberts63  I have tried that , by creating a PEM file but didn't work.

**Comment by phil1234567891011** [comment]
as for me , so far I try this, but it fails in either one of those 2 cases

class Ado:

   def init_ssl_env(self):
        if not os.path.exists(Ado.certificate_path):
            return

        try:
            if self.verify_ssl:
                # Option 1: Set CA bundle to custom certificate
                os.environ['REQUESTS_CA_BUNDLE'] = Ado.certificate_path
                self.logger.info(f"Enable SSL check - REQUESTS_CA_BUNDLE = {Ado.certificate_path}")
            else:
                # Option 2: Disable SSL verification globally (not recommended for production)
                os.environ['PYTHONHTTPSVERIFY'] = '0'
                self.logger.info(f"Disable SSL check - PYTHONHTTPSVERIFY = 0")

        except Exception as e:
            self.logger.error(f"Error setting SSL: {str(e)}")
            sys.exit(1)
