### ISSUE TITLE
'vsts build queue' should queue for current branch if in a Git repository

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-cli#92]
`vsts build queue` would be much more useful if it defaulted to the current branch if the user is in a git repository. Also, having a `git` alias for it would make sense.

**Comment by tedchamb** [comment]
@bergmeister After discussion with the team, it was decided that there are cases where we do not want the default branch from the git repo, so we have pulled out the functionality that defaults it to your current git branch as its the safer of the two approaches.  I realize that there is merit in both behaviors.   I am looking into adding some logic, so that you can configure the behavior you desire.  Stay tuned, we will be investing more in the CLI soon.
